### ISSUE TITLE
UI Design: Account Login

### ISSUE THREAD

**Issue by douglaskasper** [dkasper879/gradpath#2]
Note: All roles will be able to login from the same page.
- Input
  - [x] Username
  - [x] Password
- Buttons
  - [x] Login
  - [x] Click here to register
  - [ ] Forgot password

**Comment by Johndmattioli** [comment]
![account login](https://cloud.githubusercontent.com/assets/18059764/19053204/787186d0-897f-11e6-941e-3d0d6ae002ec.png)

**Comment by Johndmattioli** [comment]
![login_mockup](https://cloud.githubusercontent.com/assets/18059764/19057897/eb180ae2-8998-11e6-97ec-23c11214851c.png)
