### ISSUE TITLE
UI Design: Account Create

### ISSUE THREAD

**Issue by douglaskasper** [dkasper879/gradpath#3]
- Fields
  - [x] Username
  - [x] Password
  - [x] First Name
  - [x] Last Name

Note:
Account ID will be auto-assigned.
Role will be auto assigned to student.

**Comment by Johndmattioli** [comment]
![register_here_mockup](https://cloud.githubusercontent.com/assets/18059764/19053544/0047ef8a-8981-11e6-8d93-a5a110fee3db.png)
