### ISSUE TITLE
UI Design: Profile, Student

### ISSUE THREAD

**Issue by douglaskasper** [dkasper879/gradpath#4]
- [ ] Profile update page
  - Includes fields to update account.
- [ ] Saved search page
  - Includes list of all past searches.
  - Ability to click on a past search, which will perform the search using those options.
- [ ] Courses taken page
  - Includes list of all previous courses taken.

**Comment by anna-safavi** [comment]
![student view](https://cloud.githubusercontent.com/assets/19996468/19027782/4d3766f0-88f9-11e6-9745-2f6fdd668642.png)
