### ISSUE TITLE
UI Design: Profile, Faculty

### ISSUE THREAD

**Issue by douglaskasper** [dkasper879/gradpath#5]
- [ ] Profile update page
- [ ] Saved search page
- [ ] Browse Students page
  - Includes list of all students.
  - Ability to click a student, which will go to a page showing that student is selected.
    - Student page will allow profile updates, see their courses taken, and search under their ID.

**Comment by anna-safavi** [comment]
![faculty view](https://cloud.githubusercontent.com/assets/19996468/19027792/6c787c98-88f9-11e6-902e-f2a90b04396e.png)

**Comment by anna-safavi** [comment]
![faculty s student view](https://cloud.githubusercontent.com/assets/19996468/19052523/bf577346-897c-11e6-8f1c-eba327deffc7.png)
