### ISSUE TITLE
UI Design: Degree/Course Catalog

### ISSUE THREAD

**Issue by douglaskasper** [dkasper879/gradpath#7]
- [ ] Degree list
- [ ] Course list
  - Clicking on a course displays course info.
- [ ] Search/filter on degree/course list.

**Comment by Johndmattioli** [comment]
![degree_course_catalog](https://cloud.githubusercontent.com/assets/18059764/19054157/a08f46a8-8983-11e6-8ad1-6ffe84b1b6c9.png)
